### ISSUE TITLE
Doesn't compile > 6.7

### ISSUE THREAD

**Issue by LazyT** [chehrlic/qsqlcipher-qt6#1]
Hello,

used this repo for Qt6 until the 6.8 release came out. Now it doesn't compile anymore:

`
[  0%] Built target QSqlCipherDriverPlugin_autogen_timestamp_deps
[  1%] Automatic MOC and UIC for target QSqlCipherDriverPlugin
[  1%] Built target QSqlCipherDriverPlugin_autogen
[  1%] Running AUTOMOC file extraction for target QSqlCipherDriverPlugin
[  1%] Running moc --collect-json for target QSqlCipherDriverPlugin
[  1%] Building CXX object CMakeFiles/QSqlCipherDriverPlugin.dir/QSqlCipherDriverPlugin_autogen/mocs_compilation.cpp.o
[  1%] Building CXX object CMakeFiles/QSqlCipherDriverPlugin.dir/qsql_sqlite.cpp.o
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:45:30: Fehler: expected constructor, destructor, or type conversion before »(« token
   45 |     Q_STATIC_LOGGING_CATEGORY(lcSqlite, "qt.sql.sqlite")
      |                              ^
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp: In Funktion »int qGetColumnType(const QString&)«:
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:54:21: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [8]«, »long unsigned int« konnte nicht gefunden werden
   54 |     if (typeName == "integer"_L1 || typeName == "int"_L1)
      |                     ^~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:54:49: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [4]«, »long unsigned int« konnte nicht gefunden werden
   54 |     if (typeName == "integer"_L1 || typeName == "int"_L1)
      |                                                 ^~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:56:21: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [7]«, »long unsigned int« konnte nicht gefunden werden
   56 |     if (typeName == "double"_L1
      |                     ^~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:57:24: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [6]«, »long unsigned int« konnte nicht gefunden werden
   57 |         || typeName == "float"_L1
      |                        ^~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:58:24: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [5]«, »long unsigned int« konnte nicht gefunden werden
   58 |         || typeName == "real"_L1
      |                        ^~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:59:32: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [8]«, »long unsigned int« konnte nicht gefunden werden
   59 |         || typeName.startsWith("numeric"_L1))
      |                                ^~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:61:21: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [5]«, »long unsigned int« konnte nicht gefunden werden
   61 |     if (typeName == "blob"_L1)
      |                     ^~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:63:21: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [8]«, »long unsigned int« konnte nicht gefunden werden
   63 |     if (typeName == "boolean"_L1 || typeName == "bool"_L1)
      |                     ^~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:63:49: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [5]«, »long unsigned int« konnte nicht gefunden werden
   63 |     if (typeName == "boolean"_L1 || typeName == "bool"_L1)
      |                                                 ^~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp: In Elementfunktion »QSqlIndex QSQLiteDriverPrivate::getTableInfo(QSqlQuery&, const QString&, bool) const«:
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:141:16: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [8]«, »long unsigned int« konnte nicht gefunden werden
  141 |     query.exec("PRAGMA "_L1 + schema + "table_info ("_L1 + table + u')');
      |                ^~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:141:40: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [13]«, »long unsigned int« konnte nicht gefunden werden
  141 |     query.exec("PRAGMA "_L1 + schema + "table_info ("_L1 + table + u')');
      |                                        ^~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:156:34: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [8]«, »long unsigned int« konnte nicht gefunden werden
  156 |         if (isPk && (typeName == "integer"_L1))
      |                                  ^~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp: In Elementfunktion »virtual bool QSQLiteDriver::open(const QString&, const QString&, const QString&, const QString&, int, const QString&)«:
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:765:45: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [22]«, »long unsigned int« konnte nicht gefunden werden
  765 |     static const auto regexpConnectOption = "QSQLITE_ENABLE_REGEXP"_L1;
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:773:31: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [21]«, »long unsigned int« konnte nicht gefunden werden
  773 |         if (option.startsWith("QSQLITE_BUSY_TIMEOUT"_L1)) {
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:781:30: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [19]«, »long unsigned int« konnte nicht gefunden werden
  781 |         } else if (option == "QSQLITE_USE_QT_VFS"_L1) {
      |                              ^~~~~~~~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:783:30: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [22]«, »long unsigned int« konnte nicht gefunden werden
  783 |         } else if (option == "QSQLITE_OPEN_READONLY"_L1) {
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:785:30: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [17]«, »long unsigned int« konnte nicht gefunden werden
  785 |         } else if (option == "QSQLITE_OPEN_URI"_L1) {
      |                              ^~~~~~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:787:30: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [28]«, »long unsigned int« konnte nicht gefunden werden
  787 |         } else if (option == "QSQLITE_ENABLE_SHARED_CACHE"_L1) {
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:789:30: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [37]«, »long unsigned int« konnte nicht gefunden werden
  789 |         } else if (option == "QSQLITE_NO_USE_EXTENDED_RESULT_CODES"_L1) {
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:791:30: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [38]«, »long unsigned int« konnte nicht gefunden werden
  791 |         } else if (option == "QSQLITE_ENABLE_NON_ASCII_CASE_FOLDING"_L1) {
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:793:30: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [22]«, »long unsigned int« konnte nicht gefunden werden
  793 |         } else if (option == "QSQLITE_OPEN_NOFOLLOW"_L1) {
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
In Datei, eingebunden von /tmp/qsqlcipher-qt6/qsql_sqlite.cpp:10:
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:813:23: Fehler: »lcSqlite« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »SQLite«?
  813 |             qCWarning(lcSqlite, "Unsupported option '%ls'", qUtf16Printable(option.toString()));
      |                       ^~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp: In Elementfunktion »virtual bool QSQLiteDriver::beginTransaction()«:
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:899:17: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [6]«, »long unsigned int« konnte nicht gefunden werden
  899 |     if (!q.exec("BEGIN"_L1)) {
      |                 ^~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp: In Elementfunktion »virtual bool QSQLiteDriver::commitTransaction()«:
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:914:17: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [7]«, »long unsigned int« konnte nicht gefunden werden
  914 |     if (!q.exec("COMMIT"_L1)) {
      |                 ^~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp: In Elementfunktion »virtual bool QSQLiteDriver::rollbackTransaction()«:
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:929:17: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [9]«, »long unsigned int« konnte nicht gefunden werden
  929 |     if (!q.exec("ROLLBACK"_L1)) {
      |                 ^~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp: In Elementfunktion »virtual QStringList QSQLiteDriver::tables(QSql::TableType) const«:
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:948:19: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [95]«, »long unsigned int« konnte nicht gefunden werden
  948 |                   "UNION ALL SELECT name FROM sqlite_temp_master WHERE %1"_L1;
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:950:23: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [28]«, »long unsigned int« konnte nicht gefunden werden
  950 |         sql = sql.arg("type='table' OR type='view'"_L1);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:952:23: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [13]«, »long unsigned int« konnte nicht gefunden werden
  952 |         sql = sql.arg("type='table'"_L1);
      |                       ^~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:954:23: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [12]«, »long unsigned int« konnte nicht gefunden werden
  954 |         sql = sql.arg("type='view'"_L1);
      |                       ^~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:965:20: Fehler: literaler Operator für Zeichenketten »operator""_L1« mit Argumenten »const char [14]«, »long unsigned int« konnte nicht gefunden werden
  965 |         res.append("sqlite_master"_L1);
      |                    ^~~~~~~~~~~~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp: In Elementfunktion »virtual bool QSQLiteDriver::subscribeToNotification(const QString&)«:
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:1065:19: Fehler: »lcSqlite« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »SQLite«?
 1065 |         qCWarning(lcSqlite, "QSQLiteDriver::subscribeToNotification: Database not open.");
      |                   ^~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:1070:19: Fehler: »lcSqlite« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »SQLite«?
 1070 |         qCWarning(lcSqlite, "QSQLiteDriver::subscribeToNotification: Already subscribing to '%ls'.",
      |                   ^~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp: In Elementfunktion »virtual bool QSQLiteDriver::unsubscribeFromNotification(const QString&)«:
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:1087:19: Fehler: »lcSqlite« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »SQLite«?
 1087 |         qCWarning(lcSqlite, "QSQLiteDriver::unsubscribeFromNotification: Database not open.");
      |                   ^~~~~~~~
/tmp/qsqlcipher-qt6/qsql_sqlite.cpp:1092:19: Fehler: »lcSqlite« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »SQLite«?
 1092 |         qCWarning(lcSqlite, "QSQLiteDriver::unsubscribeFromNotification: Not subscribed to '%ls'.",
      |                   ^~~~~~~~
gmake[2]: *** [CMakeFiles/QSqlCipherDriverPlugin.dir/build.make:101: CMakeFiles/QSqlCipherDriverPlugin.dir/qsql_sqlite.cpp.o] Fehler 1
gmake[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/QSqlCipherDriverPlugin.dir/all] Fehler 2
gmake: *** [Makefile:146: all] Fehler 2
`

Could you please take a look at what's changed in 6.8?

Thank you,
Thomas

**Comment by chehrlic** [comment]
Ah, Q_STATIC_LOGGING_CATEGORY did not make it into 6.8, only 6.9.
Change line 42 accordingly.

**Comment by LazyT** [comment]
Thanks for the ultra fast support!
